### ISSUE TITLE
Path for video

### ISSUE THREAD

**Issue by syedburhan** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#1]
hi sir, which folder should I put the video to?

**Comment by MuhammadMoinFaisal** [comment]
Hi @syedburhan , please put in this folder 
Folder Path
yolo/v8/detect

**Comment by syedburhan** [comment]
Thank you Mr Muhammad, I did it but when I hit the enter button, nothing
happens. The file in the runs are updated

**Comment by MuhammadMoinFaisal** [comment]
Are you testing it on Google Colab or on Local IDE, if you are testing on Local IDE please watch the first few minutes of the video you will be able to run, if  issue still presists let me know
Youtube Video Link:
https://www.youtube.com/watch?v=9jRRZ-WL698
Thanks

**Comment by syedburhan** [comment]
Im using visual studio. I just download the project from github and open it
with CMD

**Comment by MuhammadMoinFaisal** [comment]
Okay can you just watch the video and follow the steps if you face any issue i am available

**Comment by syedburhan** [comment]
Okay Mr Muhammad, I'll get back to you soon. Thanks sir!!
