### ISSUE TITLE
How to develop this code?

### ISSUE THREAD

**Issue by hesamira** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#10]
Hi,

What should I change in the code to be able to use the webcam or camera online?
What should I change in the code so that I can measure the distance to obstacles with a camera?

Please help me.
Thanks.

**Comment by MuhammadMoinFaisal** [comment]
Hi, Currently, we have not integrated the code for the webcam, but we will update the repository for the webcam as well in coming week
Thanks
