### ISSUE TITLE
how to run it in IDE without using terminal?

### ISSUE THREAD

**Issue by SAITEJA245** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#12]
Hi Moin, currently, we are running the predict .py from the terminal using
`python predict.py model=yolov8l.pt source="test3.mp4" show=True`
can you tell me how to run it from the IDE in the main method of predict.py
```
if __name__ == "__main__":
    predict()
```
So that I can debug the code in pyCharm to better understand the flow!
How do I pass the model and source in 
```
if __name__ == "__main__":
    predict()
```

**Comment by MuhammadMoinFaisal** [comment]
Hi @SAITEJA245 , this requires some modification in the code and to be fair i havenot spend time on this
