### ISSUE TITLE
DEFAULT_CONFIG issue

### ISSUE THREAD

**Issue by yeongnamtan** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#15]
When I run predictions, I keep getting this DEFAULT_CONFIG error which I never had before.
Could you assist ?

WARNING ⚠️ Ultralytics settings reset to defaults. This is normal and may be due to a recent ultralytics package update, but may have overwritten previous settings. 
View and update settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.yaml'
Traceback (most recent call last):
  File "/root/ultralytics-main/ultralytics/yolo/v8/detect/tracking_fish_counting.py", line 21, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG
ImportError: cannot import name 'DEFAULT_CONFIG' from 'ultralytics.yolo.utils' (/opt/conda/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py)

**Comment by MuhammadMoinFaisal** [comment]
Please install ultralytics==8.0.0

**Comment by yeongnamtan** [comment]
I tried to do training on custom dataset for fishes.  Somehow  it takes a very long time. I am using ultralyitcs 8.0.0 to do counting. epoch reaches 100plus and still counting after 9 hours.
