### ISSUE TITLE
predict.py on custom weights

### ISSUE THREAD

**Issue by arhamlet** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#16]
I have trained a yolov8 model which has two labels. How can I pass the labels to predict.py file for the model to output classes for the custom weights. I have already tried changing the coco.yaml and coco128.yaml files but didn't work

**Comment by arhamlet** [comment]
Nevermind, I solved it. However, there is a problem when I train the model, it gets stuck exactly after 90 epochs and gives a pixart error.

**Comment by MuhammadMoinFaisal** [comment]
Hi, Please check my YouTube here i have made multiple videos regarding this
https://www.youtube.com/@muhammadmoinfaisal/videos
Thanks
