### ISSUE TITLE
'.[dev]' is not a valid editable requirement. It should either be a path to a local project or a VCS URL 

### ISSUE THREAD

**Issue by Sasukiii** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#17]
I met this problem when i want to insatll the dependencies and follow the command :pip install -e '.[dev]', I want to Know how to solve this please

**Comment by Sasukiii** [comment]
I was able to run your supplied code perfectly on pycharm's windows Powershell-based terminal, but in anaconda's virtual environment, pip install -e won't work.

**Comment by MuhammadMoinFaisal** [comment]
I will check when i get some time and will let you know
