### ISSUE TITLE
Select a class 

### ISSUE THREAD

**Issue by somamrae** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#23]
Hi. Thanks for your code.
Do you know how to set the desired class? I mean , in which file we can set a class label/number to show in the output. 
Actually, I'd like to  only show "person"s in the output, not all the COCO labels.
Thanks

**Comment by Xbotgo-Justin1** [comment]
Hello, author!
i have the same requirements. pls tell me how to deal with it. 
Thx!!!

**Comment by Liuchuang-alt** [comment]
Which platform are you running under  linux or windows

**Comment by somamrae** [comment]
> 

I am running it on Google colab

**Comment by MuhammadMoinFaisal** [comment]
You can update the predict,py file and add the if statement for example if label==person then only draw bounding boxes around detected objects

**Comment by smamraee** [comment]
Thanks,
And how about the confidence level? How i can modify the confidence level for the detection?

**Comment by smamraee** [comment]
Hi, I need to save the path for each object. Could you please tell me how I can do it?
