### ISSUE TITLE
The embedding model for feature extraction

### ISSUE THREAD

**Issue by pouryajafarzadeh** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#3]
Fantastic, I have a question, in the DeepSort method, we should extract the embedding vector of the objects (Re-ID network) for the appearance feature and use it with the motional feature (Kalman filter), how do you do this for the vehicles? Did you train a network?
Can the model extract features for any object? or it just can be used for vehicles and pedestrians?

**Comment by MuhammadMoinFaisal** [comment]
Hi pouryajafarzadeh, basically here i have used pretrained model which is trained on MS COCO dataset, you can use any custom model as well, After training the model for the detection, i initialized DeepSORT tracking algorithm in the code and assigned each detected object a Unique ID for tracking purpose, when the object disappears from the frame the unique ID is removed from the list. 
You can use this code for person vehicles, helmets,  bicycles or for any other object it is not specific to vehicles or pedistrians

**Comment by mikalbre** [comment]
Hi @MuhammadMoinFaisal,

are the embeddings in YOLOv8_Segmentation_Tracking_CustomData_Complete.ipynb file already pre-trained on the COCO dataset? While checking the .yaml file this is stated: "pretrained: False  # whether to use a pretrained model".
