### ISSUE TITLE
saving tracking result as text file

### ISSUE THREAD

**Issue by aliddp** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#4]
Hi Muhammad
Is there any way to save tracking results as a text file in a format like this:
Frame_id, object_id, class, x_center, y_center, width, height

**Comment by MuhammadMoinFaisal** [comment]
Hi @aliddp , this will be updated in the github repo in few days surely

**Comment by smamraee** [comment]
> Hi @aliddp , this will be updated in the github repo in few days surely

Hi, Did you update that? I need to save the tracking results as @aliddp said. 
Thanks
