### ISSUE TITLE
No ultralytics.yolo module

### ISSUE THREAD

**Issue by ivanatus** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#41]
Traceback of the error:
C:\Users\Ivana\YOLOv8-DeepSORT-Object-Tracking\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True
Traceback (most recent call last):
  File "C:\Users\Ivana\YOLOv8-DeepSORT-Object-Tracking\ultralytics\yolo\v8\detect\predict.py", line 13, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
ModuleNotFoundError: No module named 'ultralytics.yolo'

I already installed ultralytics previously (pip show ultralytics shows ultralytics information) and I followed instructions step by step for setting up. I am trying to run this in Anaconda Prompt on Windows 10.

**Comment by Lan1tan** [comment]
yes , this error i have same.How to solve

**Comment by hxxx151** [comment]
yes, I also have this problem. What should I do?

**Comment by shiyou99** [comment]
It's the ultralytics version error. Try "pip install ultralytics==8.0.3"

**Comment by ivanatus** [comment]
> It's the ultralytics version error. Try "pip install ultralytics==8.0.3"

This solve the problem, thank you.
