### ISSUE TITLE
Custom Model from Different version of Ultralytics Not Working

### ISSUE THREAD

**Issue by rabinsubedi** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#6]
Hello,

I am trying to run my custom model in this tracking code. It seems like this code works with ultralytics<=8.0.10. When I use my custom model trained with latest ultralytics, it doesn't work with the lower version of ultralytics (detection and tracking don't work). When I try to train model with lower version of ultralytics (which actually works with this tracking code), the training shows 'nan' loss (picture below). Can anyone please help?
Thanks!

![image](https://user-images.githubusercontent.com/61395363/221233042-c95b2b39-0356-416c-a145-738d7c3beb34.png)

**Comment by MuhammadMoinFaisal** [comment]
Hi @rabinsubedi, please try to train for atleast 10 epochs and if still the nan loss presists then please review your dataset
