### ISSUE TITLE
AttributeError:             'IterableSimpleNamespace' object has no attribute 'parent'. This may be caused by a modified or out of date ultralytics

### ISSUE THREAD

**Issue by mmcuavqgc** [MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking#7]
Hello, I encountered this problem when running；

(yolov8) F:\ultralytics>python .\ultralytics\yolo\v8\detect\predict_deepsort.py model=yolov8l.pt source="test3.mp4" show=True
Traceback (most recent call last):
  File "F:\ultralytics\ultralytics\yolo\v8\detect\predict_deepsort.py", line 308, in <module>
    @hydra.main(version_base=None, config_path=str(DEFAULT_CFG.parent), config_name=DEFAULT_CFG.name)
  File "D:\Users\liush\Anaconda3\envs\yolov8\lib\site-packages\ultralytics\yolo\utils\__init__.py", line 118, in __getattr__
    raise AttributeError(f"""
AttributeError:
            'IterableSimpleNamespace' object has no attribute 'parent'. This may be caused by a modified or out of date ultralytics
            'default.yaml' file.
Please update your code with 'pip install -U ultralytics' and if necessary replace
            D:\Users\liush\Anaconda3\envs\yolov8\Lib\site-packages\ultralytics\yolo\cfg\default.yaml with the latest version from
            https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/default.yaml

**Comment by MuhammadMoinFaisal** [comment]
Please follow the instructions in this video
https://www.youtube.com/watch?v=nkptX_vXJKo
And then run 
Thanks

**Comment by mmcuavqgc** [comment]
> Please follow the instructions in this video https://www.youtube.com/watch?v=nkptX_vXJKo And then run Thanks

ok,i will try

**Comment by mmcuavqgc** [comment]
> > Please follow the instructions in this video https://www.youtube.com/watch?v=nkptX_vXJKo And then run Thanks
> 
> ok,i will try

There are still problems。like the problems 5;https://github.com/MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking/issues/5

(yolov8) F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True
Traceback (most recent call last):
  File "F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect\predict.py", line 14, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG, ROOT, ops
ImportError: cannot import name 'DEFAULT_CONFIG' from '

**Comment by mmcuavqgc** [comment]
> > > Please follow the instructions in this video https://www.youtube.com/watch?v=nkptX_vXJKo And then run Thanks
> > 
> > 
> > ok,i will try
> 
> There are still problems。like the problems 5;#5
> 
> (yolov8) F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True Traceback (most recent call last): File "F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect\predict.py", line 14, in from ultralytics.yolo.utils import DEFAULT_CONFIG, ROOT, ops ImportError: cannot import name 'DEFAULT_CONFIG' from '

my ultralytics version is  ultralytics-8.0.49

**Comment by mmcuavqgc** [comment]
> > > > Please follow the instructions in this video https://www.youtube.com/watch?v=nkptX_vXJKo And then run Thanks
> > > 
> > > 
> > > ok,i will try
> > 
> > 
> > There are still problems。like the problems 5;#5
> > (yolov8) F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True Traceback (most recent call last): File "F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect\predict.py", line 14, in from ultralytics.yolo.utils import DEFAULT_CONFIG, ROOT, ops ImportError: cannot import name 'DEFAULT_CONFIG' from '
> 
> my ultralytics version is ultralytics-8.0.49
I compared the new version of the code. Is it because I use the new code and your project uses the old version
![image](https://user-images.githubusercontent.com/53895729/222888486-229737ad-0952-4586-b3f3-846099ac5565.png)

**Comment by mmcuavqgc** [comment]
> > > > Please follow the instructions in this video https://www.youtube.com/watch?v=nkptX_vXJKo And then run Thanks
> > > 
> > > 
> > > ok,i will try
> > 
> > 
> > There are still problems。like the problems 5;#5
> > (yolov8) F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True Traceback (most recent call last): File "F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect\predict.py", line 14, in from ultralytics.yolo.utils import DEFAULT_CONFIG, ROOT, ops ImportError: cannot import name 'DEFAULT_CONFIG' from '
> 
> my ultralytics version is ultralytics-8.0.49



> > > > Please follow the instructions in this video https://www.youtube.com/watch?v=nkptX_vXJKo And then run Thanks
> > > 
> > > 
> > > ok,i will try
> > 
> > 
> > There are still problems。like the problems 5;#5
> > (yolov8) F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect>python predict.py model=yolov8l.pt source="test3.mp4" show=True Traceback (most recent call last): File "F:\YOLOv8-DeepSORT\ultralytics\yolo\v8\detect\predict.py", line 14, in from ultralytics.yolo.utils import DEFAULT_CONFIG, ROOT, ops ImportError: cannot import name 'DEFAULT_CONFIG' from '
> 
> my ultralytics version is ultralytics-8.0.49
I replaced the version of ultralytics and it can work normally. I wonder if you can update the project's ultralytics to the latest version.
Anaconda3\envs\yolov8\Lib\site-packages\ultralytics
